name: –ü—Ä–æ–≤–µ—Ä–∫–∞ PHP –∫–æ–¥–∞ üêò (Windows)
on: [push]
jobs:
  check-syntax:
    runs-on: self-hosted 
    steps:
      - name: –°–∫–∞—á–∏–≤–∞–µ–º –∫–æ–¥ (Checkout)
        uses: actions/checkout@v3
      - name: –ü—Ä–æ–≤–µ—Ä–∫–∞ —Å–∏–Ω—Ç–∞–∫—Å–∏—Å–∞
        run: |
          Get-ChildItem -Recurse -Filter "*.php" | ForEach-Object { 
            php -l $_.FullName 
          }
